a1

diff --git a/platforms/substrate/charts/substrate-node/templates/statefulset.yaml b/platforms/substrate/charts/substrate-node/templates/statefulset.yaml
--- a/platforms/substrate/charts/substrate-node/templates/statefulset.yaml
+++ b/platforms/substrate/charts/substrate-node/templates/statefulset.yaml
@@ -56,51 +56,54 @@ spec:
               
               echo ">>> 3 <<<"
 
-              aura_secretPhrase=$(kubectl get secret "substrate-node-validator-1-keys" --namespace gensub -o json | jq -r '.data["substrate-node-keys"]' | base64 -d | jq -r '.data.aura_file_b64' | base64 -d | jq -r '.secretPhrase')
+              aura_secretPhrase=$(kubectl get secret "substrate-node-{{ .Release.Name }}-keys" --namespace gensub -o json | jq -r '.data["substrate-node-keys"]' | base64 -d | jq -r '.data.aura_file_b64' | base64 -d | jq -r '.secretPhrase')
               echo "aura_secretPhrase: $aura_secretPhrase"
-              gran_secretPhrase=$(kubectl get secret "substrate-node-validator-1-keys" --namespace gensub -o json | jq -r '.data["substrate-node-keys"]' | base64 -d | jq -r '.data.grandpa_file_b64' | base64 -d | jq -r '.secretPhrase')
+              gran_secretPhrase=$(kubectl get secret "substrate-node-{{ .Release.Name }}-keys" --namespace gensub -o json | jq -r '.data["substrate-node-keys"]' | base64 -d | jq -r '.data.grandpa_file_b64' | base64 -d | jq -r '.secretPhrase')
               echo "gran_secretPhrase: $gran_secretPhrase"
-              node_key=$(kubectl get secret "substrate-node-validator-1-keys" --namespace gensub -o json | jq -r '.data["substrate-node-keys"]' | base64 -d | jq -r '.data.node_key')
+              node_key=$(kubectl get secret "substrate-node-{{ .Release.Name }}-keys" --namespace gensub -o json | jq -r '.data["substrate-node-keys"]' | base64 -d | jq -r '.data.node_key')
               echo "node_key: $node_key"
-              node_id=$(kubectl get secret "substrate-node-validator-1-keys" --namespace gensub -o json | jq -r '.data["substrate-node-keys"]' | base64 -d | jq -r '.data.node_id')
+              node_id=$(kubectl get secret "substrate-node-{{ .Release.Name }}-keys" --namespace gensub -o json | jq -r '.data["substrate-node-keys"]' | base64 -d | jq -r '.data.node_id')
               echo "node_id: $node_id"
 
               echo ">>> 4 <<<"
 
-              ./dscp-node key insert --base-path /data \
-                --chain /data/chainspec.json \
-                --key-type gran \
-                --scheme ed25519 \
-                --suri /secrets/grandpa_seed \
-                && echo "Inserted key gran into Keystore" \
-                || echo "Failed to insert key gran into Keystore."
-              ./dscp-node key insert --base-path /data \
-                --chain /data/chainspec.json \
-                --key-type aura \
-                --scheme sr25519 \
-                --suri /secrets/aura_seed \
-                && echo "Inserted key aura into Keystore" \
-                || echo "Failed to insert key aura into Keystore."
+              # ./dscp-node key insert --base-path /data \
+              #   --chain /data/chainspec.json \
+              #   --key-type gran \
+              #   --scheme ed25519 \
+              #   --suri /secrets/grandpa_seed \
+              #   && echo "Inserted key gran into Keystore" \
+              #   || echo "Failed to insert key gran into Keystore."
+              
+              # ./dscp-node key insert --base-path /data \
+              #   --chain /data/chainspec.json \
+              #   --key-type aura \
+              #   --scheme sr25519 \
+              #   --suri /secrets/aura_seed \
+              #   && echo "Inserted key aura into Keystore" \
+              #   || echo "Failed to insert key aura into Keystore."
+
+              ./dscp-node key insert --base-path=/data --chain=/data/chainspec.json --key-type=aura --scheme=Sr25519 --suri="${aura_secretPhrase}" && echo "Inserted key aura into Keystore" || echo "Failed to insert key aura into Keystore."
+              ./dscp-node key insert --base-path=/data --chain=/data/chainspec.json --key-type=gran --scheme=Ed25519 --suri="${gran_secretPhrase}" && echo "Inserted key gran into Keystore" || echo "Failed to insert key gran into Keystore."
 
               echo ">>> 5 <<<"
 
-              EXTERNAL_ADDRESS=${POD_NAME}-rc-p2p.oem-subs.svc.cluster.local
+              EXTERNAL_ADDRESS=${POD_NAME}.sub.blockchaincloudpoc-develop.com
               echo "EXTERNAL_ADDRESS=${EXTERNAL_ADDRESS}"
-              EXTERNAL_P2P_PORT=30333
+              EXTERNAL_P2P_PORT=15031
               echo "EXTERNAL_P2P_PORT=${EXTERNAL_P2P_PORT}"
-              RELAY_CHAIN_P2P_PORT=30333
+              RELAY_CHAIN_P2P_PORT=15031
               echo "RELAY_CHAIN_P2P_PORT=${RELAY_CHAIN_P2P_PORT}"
 
               echo ">>> 6 <<<"
 
+              echo "POD_NAME=${POD_NAME}"
               exec ./dscp-node \
               --name=${POD_NAME} \
               --base-path=/data/ \
               --chain=/data/chainspec.json \
-              {{- if or (eq .Values.node.role "authority") (eq .Values.node.role "validator") }} 
               --validator \
-              --bootnodes '/dns4/<FIRST_NODE>-rc-p2p.oem-subs.svc.cluster.local/tcp/30333/p2p/${FIRST_NODE_node_id}' \
-              {{- end }}
+              --bootnodes '/dns4/validator-1-substrate-node-0.sub.blockchaincloudpoc-develop.com/tcp/15030/p2p/12D3KooWP1Trq8pH1LVFm52YTbnu6veVSLV8pXQByYZGehr3xzEM' \
               --node-key ${node_key} \
               --rpc-external --ws-external --rpc-methods=Unsafe --rpc-cors=all --unsafe-ws-external --unsafe-rpc-external \
               --public-addr=/dns4/${EXTERNAL_ADDRESS}/tcp/${EXTERNAL_P2P_PORT} \
@@ -142,19 +145,6 @@ spec:
               path: /health
               port: http-rpc
           {{- end }}
-          {{- if .Values.node.enableReadinessProbe }}
-          # Continuously retry the connection to the WS endpoint every 10s for 24h until success before marking the container as ready
-          # If the WS endpoint is still not reachable (ie. node not fully synced) after 24 hours have passed, the container will be stuck in 'Not Ready' state
-          readinessProbe:
-            failureThreshold: 8640
-            initialDelaySeconds: 10
-            periodSeconds: 10
-            successThreshold: 1
-            timeoutSeconds: 1
-            # Important: the readiness probe will only work properly if the WS endpoint is exposed with --ws-external
-            tcpSocket:
-              port: websocket-rpc
-          {{- end }}
           resources:
           {{- toYaml .Values.node.resources | nindent 12 }}
           volumeMounts:
@@ -165,42 +155,22 @@ spec:
           - name: package-manager
             mountPath: /scripts/package-manager.sh
             subPath: package-manager.sh
-          {{- if .Values.node.persistGeneratedNodeKey }}
-          {{- else if .Values.node.customNodeKey }}
-          - mountPath: /tmp/
-            name: custom-node-key
-            readOnly: true
-          {{- end }}
-          resources:
-          {{- toYaml .Values.jaegerAgent.resources | nindent 12 }}
           ports:
-            - name: jaeger-compact
-              containerPort: {{ .Values.jaegerAgent.ports.compactPort }}
-              protocol: UDP
-            - name: jaeger-binary
-              containerPort: {{ .Values.jaegerAgent.ports.binaryPort }}
-              protocol: UDP
-            - name: http
-              containerPort: {{ .Values.jaegerAgent.ports.samplingPort }}
-              protocol: TCP
             - name: admin
               containerPort: 14271
               protocol: TCP
-          livenessProbe:
-            httpGet:
-              path: /
-              port: admin
-          readinessProbe:
-            httpGet:
-              path: /
-              port: admin
-        {{- end}}
+          # livenessProbe:
+          #   httpGet:
+          #     path: /
+          #     port: admin
+          # readinessProbe:
+          #   httpGet:
+          #     path: /
+          #     port: admin
         {{- with .Values.extraContainers }}
         {{- toYaml . | nindent 8 }}
         {{- end}}
       serviceAccountName: {{ $serviceAccountName }}
-      securityContext:
-      {{- toYaml .Values.podSecurityContext | nindent 8 }}
       terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
       {{- with .Values.nodeSelector }}
       nodeSelector:
@@ -215,11 +185,6 @@ spec:
       {{- toYaml . | nindent 8 }}
       {{- end }}
       volumes:
-      {{- if .Values.googleCloudSdk.serviceAccountKey }}
-        - name: service-account-key
-          secret:
-            secretName: chain-data-gcs-bucket-service-account-key
-      {{- end }}
       {{- if .Values.node.persistGeneratedNodeKey }}
       {{- else if .Values.node.customNodeKey }}
         - name: custom-node-key
