full

diff --git a/platforms/quorum/charts/quorum-tlscert-gen/templates/job.yaml b/platforms/quorum/charts/quorum-tlscert-gen/templates/job.yaml
--- a/platforms/quorum/charts/quorum-tlscert-gen/templates/job.yaml
+++ b/platforms/quorum/charts/quorum-tlscert-gen/templates/job.yaml
@@ -7,13 +7,13 @@
 apiVersion: batch/v1
 kind: Job
 metadata:
-  name: "{{ include "besu-tlscert-gen.name" . }}"
+  name: "{{ include "goquorum-tlscert-gen.name" . }}"
   namespace: "{{ .Release.Namespace }}"
   annotations:
     helm.sh/hook-delete-policy: "before-hook-creation"
   labels:
-    app: "{{ include "besu-tlscert-gen.name" . }}"
-    app.kubernetes.io/name: "{{ include "besu-tlscert-gen.name" . }}"
+    app: "{{ include "goquorum-tlscert-gen.name" . }}"
+    app.kubernetes.io/name: "{{ include "goquorum-tlscert-gen.name" . }}"
     app.kubernetes.io/managed-by: {{ .Release.Service }}
     app.kubernetes.io/instance: {{ .Release.Name }}
     {{- if $.Values.labels }}
@@ -28,8 +28,8 @@ spec:
   template:
     metadata:
       labels:
-        app: "{{ include "besu-tlscert-gen.name" . }}"
-        app.kubernetes.io/name: "{{ include "besu-tlscert-gen.name" . }}"
+        app: "{{ include "goquorum-tlscert-gen.name" . }}"
+        app.kubernetes.io/name: "{{ include "goquorum-tlscert-gen.name" . }}"
         app.kubernetes.io/managed-by: {{ .Release.Service }}
         app.kubernetes.io/instance: {{ .Release.Name }}
         {{- if $.Values.labels }}
@@ -142,7 +142,7 @@ spec:
         - name: CERT_SUBJECT
           value: "{{ $.Values.settings.certSubject }}"
         - name: EXTERNAL_URL
-          value: "{{ .Release.Name }}.{{ .Values.global.proxy.externalUrlSuffix }}"
+          value: "{{ include "goquorum-tlscert-gen.name" . }}.{{ .Values.global.proxy.externalUrlSuffix }}"
         - name: COMPONENT_NS
           value: "{{ .Release.Namespace }}"
         command: ["sh", "-c"]
@@ -158,6 +158,8 @@ spec:
               done < ${1} > ${2}/${NAME}.txt
             }
 
+            echo "1-#################################-pwd:" && pwd
+
             # Set the directories path
             CERTS_CHECKS_PATH=/certificates/check_certs
             AMBASSADORTLS_PATH=/certificates/ambassadortls
@@ -170,15 +172,28 @@ spec:
             # if ambassadortls_absent file does not exist, create the certificates
             if [ -e ${CERTS_CHECKS_PATH}/ambassadortls_absent.txt ]
             then
+              echo "2-T"
               # Create the rootca directory if it doesn't exist
               mkdir -p ${ROOTCA_PATH}
               cd ${ROOTCA_PATH}
+              echo "2-#################################-pwd:" && pwd
 
               # Generates the rootCA certificates
               openssl genrsa -out rootca.key 2048
               openssl req -x509 -new -nodes -key rootca.key -sha256 -days 1024 -out rootca.pem -subj "/${CERT_SUBJECT}"
+
+              echo "3-#################################-pwd:" && pwd
+              echo "3-#################################-rootca.key:" && pwd && cat rootca.key
+              echo "3-#################################-rootca.key:END"
+              echo "3-#################################-rootca.pem:" && pwd && cat rootca.pem
+              echo "3-#################################-rootca.pem:END"
+
+
               # Generates the openssl file for domain
               cd ${AMBASSADORTLS_PATH}
+
+              echo "4-#################################-EXTERNAL_URL:" && pwd && echo $EXTERNAL_URL
+              echo "4-#################################-EXTERNAL_URL:END"
               echo "[req]
               req_extensions = v3_req
               distinguished_name = dn
@@ -189,7 +204,7 @@ spec:
               subjectAltName = @alt_names
               [alt_names]
               DNS.1 = ${EXTERNAL_URL}
-              DNS.2 = {{ include "besu-tlscert-gen.fullname" . }}.{{ .Release.Namespace }}
+              DNS.2 = {{ include "goquorum-tlscert-gen.fullname" . }}.{{ .Release.Namespace }}
               DNS.3 = tessera-{{ .Release.Name }}.{{ .Release.Namespace }}
               " > openssl.conf
               # Generates the ambassador tls certificates
@@ -198,25 +213,53 @@ spec:
               openssl x509 -req -in node.csr -CA ${ROOTCA_PATH}/rootca.pem -CAkey ${ROOTCA_PATH}/rootca.key -CAcreateserial -out node.pem -days 1000 -sha256 -extfile "openssl.conf" -extensions v3_req
               cat node.pem > certchain.pem
               cat ${ROOTCA_PATH}/rootca.pem >> certchain.pem
+
+              echo "5-#################################-node.key:" && pwd && cat node.key
+              echo "5-#################################-node.key:END"
+              echo "6-#################################-node.csr:" && pwd && cat node.csr
+              echo "6-#################################-node.csr:END"
+              echo "7-#################################-node.pem:" && pwd && cat node.pem
+              echo "7-#################################-node.pem:END"
+              echo "8-#################################-certchain.pem:" && pwd && cat certchain.pem
+              echo "8-#################################-certchain.pem:END"
               
               # Check if TM_TLS_ENABLED is true
               if [ "$TM_TLS_ENABLED" == "true"  ]
               then
-                # Generate crypto for besu nodes and knownserver file
-                openssl genrsa -out besu-node.key 2048
-                openssl req -new -key besu-node.key -out besu-node.csr -subj "/CN=${EXTERNAL_URL}"
-                openssl x509 -req -in besu-node.csr -CA ${ROOTCA_PATH}/rootca.pem -CAkey ${ROOTCA_PATH}/rootca.key -CAcreateserial -out besu-node.pem -days 500 -sha256
-                cat besu-node.key besu-node.pem > besu_certificates.pem
-                openssl pkcs12 -export -in besu_certificates.pem -out besu-node.pkcs12 -password pass:changeme -name myAlias -noiter -nomaciter
-                echo "changeme" > besu-password
-                openssl x509 -in certchain.pem -noout -fingerprint -sha256 > besu-certchain-sha256
-                export DIGEST=$(awk '{print $2}' besu-certchain-sha256 | sed -n 's/Fingerprint=\(.*\)/\1/p')
-                printf '%s\n' "tessera-*.${COMPONENT_NS}:${TM_CLIENT_PORT} $DIGEST" "${EXTERNAL_URL} $DIGEST" > besu-knownServer
+                echo "3-T"
+                # Generate crypto for goquorum nodes and knownserver file
+                openssl genrsa -out goquorum-node.key 2048
+                openssl req -new -key goquorum-node.key -out goquorum-node.csr -subj "/CN=${EXTERNAL_URL}"
+                openssl x509 -req -in goquorum-node.csr -CA ${ROOTCA_PATH}/rootca.pem -CAkey ${ROOTCA_PATH}/rootca.key -CAcreateserial -out goquorum-node.pem -days 500 -sha256
+                cat goquorum-node.key goquorum-node.pem > goquorum_certificates.pem
+
+                echo "cat goquorum-node.key"
+                cat goquorum-node.key
+
+                echo "cat goquorum-node.pem"
+                cat goquorum-node.pem
+
+                echo "###############-1"
+                cat goquorum_certificates.pem
+                echo "###############-1-end"
+
+                openssl pkcs12 -export -in goquorum_certificates.pem -out goquorum-node.pkcs12 -password pass:changeme -name myAlias -noiter -nomaciter
+                echo "changeme" > goquorum-password
+
+                echo "###############-2"
+                cat goquorum-node.pkcs12
+                echo "###############-2-end"
+
+                openssl x509 -in certchain.pem -noout -fingerprint -sha256 > goquorum-certchain-sha256
+                export DIGEST=$(awk '{print $2}' goquorum-certchain-sha256 | sed -n 's/Fingerprint=\(.*\)/\1/p')
+                printf '%s\n' "tessera-*.${COMPONENT_NS}:${TM_CLIENT_PORT} $DIGEST" "${EXTERNAL_URL} $DIGEST" > goquorum-knownServer
               fi;
             fi;
             # Create necessary subdirectories for certificate storage
             mkdir -p ${FORMAT_CERTIFICATE_PATH}/rootca
             mkdir -p ${FORMAT_CERTIFICATE_PATH}/ambassadortls
+
+            echo "4-T"
 
             # Source the bevel-vault.sh script to perform the Vault-CURD operations
             . /scripts/bevel-vault.sh
@@ -224,9 +267,14 @@ spec:
             echo "Getting the vault Token.."
             vaultBevelFunc 'init'
 
+            echo "5-T-ls"
+            ls
+            echo "5-T-ls-end"
+
             # Check if ambassadortls certificates are absent, then save them to Vault
             if [ -e ${CERTS_CHECKS_PATH}/ambassadortls_absent.txt ]
             then
+              echo "6-T"
               # Encode the certificate and key files in base64 format
               base64 ${ROOTCA_PATH}/rootca.key > ${ROOTCA_PATH}/encode_rootca.key
               base64 ${ROOTCA_PATH}/rootca.pem > ${ROOTCA_PATH}/encode_rootca.pem
@@ -249,19 +297,21 @@ spec:
               if [ "$TM_TLS_ENABLED" == "true" ]
               then
                 # Encode additional certificate files when tmTls is true
-                base64 ${AMBASSADORTLS_PATH}/besu-node.pkcs12 > ${AMBASSADORTLS_PATH}/encode_besu-node.pkcs12
-                base64 ${AMBASSADORTLS_PATH}/besu-password > ${AMBASSADORTLS_PATH}/encode_besu-password
-                base64 ${AMBASSADORTLS_PATH}/besu-knownServer > ${AMBASSADORTLS_PATH}/encode_besu-knownServer
+                base64 ${AMBASSADORTLS_PATH}/goquorum-node.pkcs12 > ${AMBASSADORTLS_PATH}/encode_goquorum-node.pkcs12
+                base64 ${AMBASSADORTLS_PATH}/goquorum-password > ${AMBASSADORTLS_PATH}/encode_goquorum-password
+                base64 ${AMBASSADORTLS_PATH}/goquorum-knownServer > ${AMBASSADORTLS_PATH}/encode_goquorum-knownServer
                 
                 # Format the additional certificate files for saving in the vault
-                formatCertificate "${AMBASSADORTLS_PATH}/encode_besu-node.pkcs12" "${FORMAT_CERTIFICATE_PATH}/ambassadortls"
-                formatCertificate "${AMBASSADORTLS_PATH}/encode_besu-password" "${FORMAT_CERTIFICATE_PATH}/ambassadortls"
-                formatCertificate "${AMBASSADORTLS_PATH}/encode_besu-knownServer" "${FORMAT_CERTIFICATE_PATH}/ambassadortls"
+                formatCertificate "${AMBASSADORTLS_PATH}/encode_goquorum-node.pkcs12" "${FORMAT_CERTIFICATE_PATH}/ambassadortls"
+                formatCertificate "${AMBASSADORTLS_PATH}/encode_goquorum-password" "${FORMAT_CERTIFICATE_PATH}/ambassadortls"
+                formatCertificate "${AMBASSADORTLS_PATH}/encode_goquorum-knownServer" "${FORMAT_CERTIFICATE_PATH}/ambassadortls"
 
                 # Read the additional formatted certificate files
-                KEYSTORE_FORMAT=$(cat ${FORMAT_CERTIFICATE_PATH}/ambassadortls/encode_besu-node.pkcs12.txt)
-                PASSWORD_FORMAT=$(cat ${FORMAT_CERTIFICATE_PATH}/ambassadortls/encode_besu-password.txt)
-                KNOWNSERVER_FORMAT=$(cat ${FORMAT_CERTIFICATE_PATH}/ambassadortls/encode_besu-knownServer.txt)
+                KEYSTORE_FORMAT=$(cat ${FORMAT_CERTIFICATE_PATH}/ambassadortls/encode_goquorum-node.pkcs12.txt)
+                PASSWORD_FORMAT=$(cat ${FORMAT_CERTIFICATE_PATH}/ambassadortls/encode_goquorum-password.txt)
+                KNOWNSERVER_FORMAT=$(cat ${FORMAT_CERTIFICATE_PATH}/ambassadortls/encode_goquorum-knownServer.txt)
+
+                echo "KEYSTORE_FORMAT: $KEYSTORE_FORMAT"
                 
                 # Create a JSON file with the data to be saved in the vault when tmTls is true
                 echo "
@@ -309,10 +359,20 @@ spec:
                 PASSWORD=$(echo ${VAULT_SECRET} | jq -r '.["password"]')
                 KNOWNSERVER=$(echo ${VAULT_SECRET} | jq -r '.["knownServer"]')
 
+                echo "CA_PEM: $CA_PEM"
+                echo "CA_KEY: $CA_KEY"
+                echo "AMBASSADORCRT: $AMBASSADORCRT"
+                echo "AMBASSADORKEY: $AMBASSADORKEY"
+                echo "KEYSTORE: $KEYSTORE"
+                echo "PASSWORD: $PASSWORD"
+                echo "KNOWNSERVER: $KNOWNSERVER"
+
+
                 # Check if any of the certificate and key fields are missing, empty or having any kind of error
                 for field in "$CA_PEM" "$CA_KEY" "$AMBASSADORCRT" "$AMBASSADORKEY" "$KEYSTORE" "$PASSWORD" "$KNOWNSERVER"
                 do
-                  if [ "$field" = "null"  ] || [[ "$field" = "parse error"* ]] || [ "$field" = "" ]
+                  # if [ -z "$field" ] || [ "$field" = "null" ] || echo "$field" | grep -q "errors"; then
+                  if [ "$field" = "null"  ] || [[ "$field" = "parse error"* ]] || [ "$field" = "" ] # NEW L-Incorrect-T-M
                   then
                     AMBASSADORTLS_CERT_WRITTEN=false
                     break
@@ -346,13 +406,19 @@ spec:
               # Delete the same JSON file that we created to perform the write operation in the vault
               rm payload.json
             fi;
+
+            echo "7-T"
+
             # Create tls secret with the certificates
-            kubectl get configmap --namespace {{ .Release.Namespace }} {{ include "besu-tlscert-gen.name" . }}-tls-certs
-            if [ $? -ne 0 ]; then
-              kubectl create secret tls --namespace {{ .Release.Namespace }} {{ include "besu-tlscert-gen.name" . }}-tls-certs \
+            # kubectl get configmap --namespace {{ .Release.Namespace }} {{ include "goquorum-tlscert-gen.name" . }}-tls-certs # INCORRECT
+            if ! kubectl get secret tls --namespace {{ .Release.Namespace }} {{ include "goquorum-tlscert-gen.name" . }}-tls-certs &>/dev/null; then
+              echo "8-T"
+              kubectl create secret tls --namespace {{ .Release.Namespace }} {{ include "goquorum-tlscert-gen.name" . }}-tls-certs \
               --cert=${AMBASSADORTLS_PATH}/certchain.pem \
               --key=${AMBASSADORTLS_PATH}/node.key
             fi
+
+            echo "# COMPLETED #"
         volumeMounts:
           - name: certificates
             mountPath: /certificates
