[ci skip] Pushing deployment files for namespace
Signed-off-by: saurabhkumarkardam <saurabh.kumar.kardam@accenture.com>

diff --git a/platforms/quorum/charts/gen-node/templates/node-hook-pre-delete.yaml b/platforms/quorum/charts/gen-node/templates/node-hook-pre-delete.yaml
--- a/platforms/quorum/charts/gen-node/templates/node-hook-pre-delete.yaml
+++ b/platforms/quorum/charts/gen-node/templates/node-hook-pre-delete.yaml
@@ -43,28 +43,27 @@ spec:
 
               echo "{{ template "goquorum-node.fullname" . }} Pre Delete hook ..."
 
-              # Get the content of the ConfigMap and save it to a file
-              if kubectl get configmap static-nodes-config -n genesis -o json | jq -r '.data["static-nodes.json"]' > ./static-nodes.json; then
-                  echo "Content of the ConfigMap has been saved to static-nodes.json"
-                  existingStaticNodes=$(cat ./static-nodes.json)
-              else
-                  echo "Error: Failed to get content of ConfigMap."
-                  exit 1
+              # Check if the ConfigMap exists
+              if kubectl get configmap static-nodes-config -n genesis &>/dev/null; then
+                  # Get the content of the ConfigMap and save it to a file
+                  if kubectl get configmap static-nodes-config -n genesis -o json | jq -r '.data["static-nodes.json"]' > ./static-nodes.json; then
+                      existingStaticNodes=$(cat ./static-nodes.json)
+                  else
+                      echo "Error: Failed to get content of ConfigMap."
+                      exit 1
+                  fi
               fi
 
               ## Check if the secret exists
               if kubectl get secret "{{ template "goquorum-node.fullname" . }}-keys" -n {{ .Release.Namespace }} >/dev/null 2>&1; then
-                  # Retrieve nodekey_pub from the secret
-                  nodekey_pub=$(kubectl get secret "{{ template "goquorum-node.fullname" . }}-keys" -n {{ .Release.Namespace }} -o json | jq -r '.data["nodekey.pub"]' | base64 -d)
-                  # Check if nodekey_pub is empty
-                  if [ -z "$nodekey_pub" ]; then
-                      echo "Error: Retrieved nodekey.pub is empty."
-                      exit 1
-                  fi
-                  deleteNode="enode://$nodekey_pub@{{ include "goquorum-node.enodeURL" . }}?discport=0"
-              else
-                  echo "Error: Secret containing nodekey.pub does not exist."
-                  exit 1
+                # Retrieve nodekey_pub from the secret
+                nodekey_pub=$(kubectl get secret "{{ template "goquorum-node.fullname" . }}-keys" -n {{ .Release.Namespace }} -o json | jq -r '.data["nodekey.pub"]' | base64 -d)
+                # Check if nodekey_pub is empty
+                if [ -z "$nodekey_pub" ]; then
+                    echo "Error: Retrieved nodekey.pub is empty."
+                    exit 1
+                fi
+                deleteNode="enode://$nodekey_pub@{{ include "goquorum-node.enodeURL" . }}?discport=0"
               fi
 
               # Check if the newStaticNode is already present in existingStaticNodes
@@ -76,12 +75,15 @@ spec:
               # Update the static-nodes.json file
               echo "$existingStaticNodes" > ./static-nodes.json
 
-              # Apply the updated static-nodes.json to the ConfigMap
-              if kubectl create configmap static-nodes-config --from-file=./static-nodes.json -n {{ .Release.Namespace }} --dry-run=client -o yaml | kubectl replace -f -; then
-                  echo "ConfigMap updated successfully."
-              else
-                  echo "Error: Failed to update ConfigMap."
-                  exit 1
+              # Check if the ConfigMap exists
+              if kubectl get configmap static-nodes-config -n {{ .Release.Namespace }} &>/dev/null; then
+                  # Apply the updated static-nodes.json to the ConfigMap
+                  if kubectl create configmap static-nodes-config --from-file=./static-nodes.json -n {{ .Release.Namespace }} --dry-run=client -o yaml | kubectl replace -f -; then
+                      echo "ConfigMap updated successfully."
+                  else
+                      echo "Error: Failed to update ConfigMap."
+                      exit 1
+                  fi
               fi
 
               if kubectl get secret "{{ template "goquorum-node.fullname" . }}-keys" -n {{ .Release.Namespace }} >/dev/null 2>&1; then
diff --git a/platforms/quorum/charts/gen-node/templates/pre-pod.yaml b/platforms/quorum/charts/gen-node/templates/pre-pod.yaml
--- a/platforms/quorum/charts/gen-node/templates/pre-pod.yaml
+++ b/platforms/quorum/charts/gen-node/templates/pre-pod.yaml
@@ -7,7 +7,7 @@ metadata:
   annotations:
     "helm.sh/hook": pre-install
     "helm.sh/hook-weight": "0"
-    "helm.sh/hook-delete-policy": "hook-succeeded" # "before-hook-creation"
+    "helm.sh/hook-delete-policy": "before-hook-creation" # "hook-succeeded" | "before-hook-creation"
   labels:
     app.kubernetes.io/name: pre-install-hook
     app.kubernetes.io/component: keygen
@@ -63,29 +63,46 @@ spec:
                   # apt install tree
 
                   safeWriteSecret() {
-                    local dir="$1"
-                    local fpath="$2"
-                    # vaultBevelFunc "readJson" "${VAULT_SECRET_ENGINE}/${VAULT_SECRET_PREFIX}/quorum-node-{{ .Release.Name }}-keys"
-                    vaultBevelFunc "readJson" "${VAULT_SECRET_ENGINE}/${VAULT_SECRET_PREFIX}/${fpath}"
-                    if [ "$SECRETS_AVAILABLE" == "no" ]
+                    local key="$1" # {{ template "goquorum-node.fullname" . }}-keys
+                    local fpath="$2" # ${dir}
+
+                    vaultBevelFunc "readJson" "${VAULT_SECRET_ENGINE}/${VAULT_SECRET_PREFIX}/${key}"
+                    if [ "$SECRETS_AVAILABLE" == "yes" ]
                     then
+                      local accountAddress=$(echo ${VAULT_SECRET} | jq -r '.["accountAddress"]')
+                      local accountKeystore=$(echo ${VAULT_SECRET} | jq -r '.["accountKeystore_base64"]' | base64 -d)
+                      local accountPassword=$(echo ${VAULT_SECRET} | jq -r '.["accountPassword"]')
+                      local accountPrivateKey=$(echo ${VAULT_SECRET} | jq -r '.["accountPrivateKey"]')
+                      local address=$(echo ${VAULT_SECRET} | jq -r '.["nodeAddress"]')
+                      local nodeKey=$(echo ${VAULT_SECRET} | jq -r '.["nodeKey"]')
+                      nodekey_pub=$(echo ${VAULT_SECRET} | jq -r '.["nodeKeyPub"]')
+                      
+                      kubectl create secret generic {{ template "goquorum-node.fullname" . }}-keys --namespace {{ .Release.Namespace }} \
+                      --from-literal=accountAddress=${accountAddress} \
+                      --from-literal=accountKeystore=${accountKeystore} \
+                      --from-literal=accountPassword=${accountPassword} \
+                      --from-literal=accountPrivateKey=${accountPrivateKey} \
+                      --from-literal=address=${address} \
+                      --from-literal=nodekey=${nodeKey} \
+                      --from-literal=nodekey.pub=${nodekey_pub}
+                    else
                       # Check if all required files exist
                       local required_files=("accountAddress" "accountKeystore" "accountPassword" "accountPrivateKey" "address" "nodekey" "nodekey.pub")
                       for file in "${required_files[@]}"; do
-                        if [ ! -f "${dir}/${file}" ]; then
-                          echo "Error: File '${file}' not found in '${dir}'" >&2
+                        if [ ! -f "${fpath}/${file}" ]; then
+                          echo "Error: File '${file}' not found in '${fpath}'" >&2
                           return 1
                         fi
                       done
                       
                       # Read data from files
-                      local accountAddress=$(cat "${dir}/accountAddress")
-                      local accountKeystore_base64=$(cat "${dir}/accountKeystore" | base64 -w 0)
-                      local accountPassword=$(cat "${dir}/accountPassword")
-                      local accountPrivateKey=$(cat "${dir}/accountPrivateKey")
-                      local address=$(cat "${dir}/address")
-                      local nodekey=$(cat "${dir}/nodekey")
-                      local nodekey_pub=$(cat "${dir}/nodekey.pub")
+                      local accountAddress=$(cat "${fpath}/accountAddress")
+                      local accountKeystore_base64=$(cat "${fpath}/accountKeystore" | base64 -w 0)
+                      local accountPassword=$(cat "${fpath}/accountPassword")
+                      local accountPrivateKey=$(cat "${fpath}/accountPrivateKey")
+                      local address=$(cat "${fpath}/address")
+                      local nodekey=$(cat "${fpath}/nodekey")
+                      local nodekey_pub=$(cat "${fpath}/nodekey.pub")
                       
                       # Construct JSON payload
                       echo "
@@ -103,8 +120,16 @@ spec:
                         }" > nodePayload.json
                       
                       # Push data to vault
-                      vaultBevelFunc 'write' "${VAULT_SECRET_ENGINE}/${VAULT_SECRET_PREFIX}/${fpath}" 'nodePayload.json'
+                      vaultBevelFunc 'write' "${VAULT_SECRET_ENGINE}/${VAULT_SECRET_PREFIX}/${key}" 'nodePayload.json'
                     fi
+                  }
+                else
+                  safeWriteSecret() {
+                  # Placeholder:
+                  # - Implement code to fetch the keys if using any cloud-native service or platform different from HashiCorp to store the keys
+                  # - After fetching the keys, create Kubernetes secrets from them
+                  # - For guidance, refer to the code written for HashiCorp Vault for the same purpose
+                  return 0
                   }
                 fi
 
@@ -112,39 +137,42 @@ spec:
                   echo "Secret does not exist. Creating secret."
                   FOLDER_PATH=$(quorum-genesis-tool --validators 0 --members 1 --bootnodes 0 \
                     {{ if .Values.node.goquorum.account.password }} --accountPassword {{ .Values.node.goquorum.account.password }} {{ end }} \
-                    --outputPath 'artifacts')
+                    --outputPath /generated-config | tail -1 | sed -e "s/^Artifacts in folder: //")
                   
-                  # Extract the directory path from the output
-                  directory=$(echo "$FOLDER_PATH" | grep -o 'artifacts/.*')
-                  # Print the directory path
-                  echo "Directory path: $directory" # NR
-                  mv $directory/* artifacts
-                  
-                  dir="./artifacts/member0"
-                  # local deployment="vault" # vault | local
+                  # dir="./artifacts/member0"
+                  dir="$FOLDER_PATH/member0"
 
-                  # Secret
-                  kubectl create secret generic {{ template "goquorum-node.fullname" . }}-keys --namespace {{ .Release.Namespace }} \
-                  --from-literal=accountAddress=$(cat "${dir}/accountAddress") \
-                  --from-literal=accountKeystore=$(cat "${dir}/accountKeystore") \
-                  --from-literal=accountPassword=$(cat "${dir}/accountPassword") \
-                  --from-literal=accountPrivateKey=$(cat "${dir}/accountPrivateKey") \
-                  --from-literal=address=$(cat "${dir}/address") \
-                  --from-literal=nodekey=$(cat "${dir}/nodekey") \
-                  --from-literal=nodekey.pub=$(cat "${dir}/nodekey.pub")
+{{- if and (ne .Values.global.cluster.provider "minikube") (.Values.global.cluster.cloudNativeServices) }}
+                  echo "Creating keys in vault for {{ template "besu-node.fullname" . }} ..."
+                  safeWriteSecret {{ template "besu-node.fullname" . }}-nodekey $FOLDER_PATH/member0/nodekey
+                  safeWriteSecret {{ template "besu-node.fullname" . }}-nodekeypub $FOLDER_PATH/member0/nodekey.pub
+                  safeWriteSecret {{ template "besu-node.fullname" . }}-enode $FOLDER_PATH/member0/nodekey.pub
+                  safeWriteSecret {{ template "besu-node.fullname" . }}-address $FOLDER_PATH/member0/address
+                  safeWriteSecret {{ template "besu-node.fullname" . }}-accountPrivateKey $FOLDER_PATH/member0/accountPrivateKey
+                  safeWriteSecret {{ template "besu-node.fullname" . }}-accountPassword $FOLDER_PATH/member0/accountPassword
+                  safeWriteSecret {{ template "besu-node.fullname" . }}-accountKeystore $FOLDER_PATH/member0/accountKeystore
+                  safeWriteSecret {{ template "besu-node.fullname" . }}-accountAddress $FOLDER_PATH/member0/accountAddress
+{{- else }}
+                  safeWriteSecret "{{ template "goquorum-node.fullname" . }}-keys" "${dir}"
+{{- end }}
 
-                  nodekey_pub=$(cat "${dir}/nodekey.pub")
-                  
-                  safeWriteSecret "${dir}" "{{ template "goquorum-node.fullname" . }}-keys"
+                  if ! kubectl get secret {{ template "goquorum-node.fullname" . }}-keys -n {{ .Release.Namespace }} &> /dev/null; then
+                    # Secret
+                    kubectl create secret generic {{ template "goquorum-node.fullname" . }}-keys --namespace {{ .Release.Namespace }} \
+                    --from-literal=accountAddress=$(cat "${dir}/accountAddress") \
+                    --from-literal=accountKeystore=$(cat "${dir}/accountKeystore") \
+                    --from-literal=accountPassword=$(cat "${dir}/accountPassword") \
+                    --from-literal=accountPrivateKey=$(cat "${dir}/accountPrivateKey") \
+                    --from-literal=address=$(cat "${dir}/address") \
+                    --from-literal=nodekey=$(cat "${dir}/nodekey") \
+                    --from-literal=nodekey.pub=$(cat "${dir}/nodekey.pub")
+                    
+                    nodekey_pub=$(cat "${dir}/nodekey.pub")
+                  fi
                 else
                   echo "Secret exists. Extract modekey.pub key"
                   nodekey_pub=$(kubectl get secret {{ template "goquorum-node.fullname" . }}-keys -n genesis -o json | jq -r '.data["nodekey.pub"]' | base64 -d)
-                fi              
-
-                # vaultBevelFunc "readJson" "${VAULT_SECRET_ENGINE}/${VAULT_SECRET_PREFIX}/quorum-genesis"
-                # echo ${VAULT_SECRET} | jq -r '.["genesis_base64"]' | base64 -d > ./genesis.json
-                # # genesis=$(echo ${VAULT_SECRET} | jq -r '.["genesis_base64"]' | base64 -d)
-                # kubectl create configmap "quorum-genesis" --from-file=./genesis.json -n {{ .Release.Namespace }}
+                fi
 
                 configmap_name="static-nodes-config"
                 # Check if the ConfigMap exists
@@ -159,28 +187,18 @@ spec:
                     echo "SN-1"
                     cat ./static-nodes.json
 
-                    # # pubkey=$(cat data/nodekey.pub)
-                    # pubkey=$(echo ${nodekey_pub})
-                    # newStaticNode="enode://$pubkey@quorum-node-{{ .Release.Name }}.{{ .Release.Namespace }}:30303?discport=0"
                     newStaticNode="enode://$nodekey_pub@{{ include "goquorum-node.enodeURL" . }}?discport=0"
-
-                    ####################################################################################################
-                    # existingStaticNodes=$(jq ". + [\"$newStaticNode\"]" <<< "$existingStaticNodes")
-                    # echo "$existingStaticNodes" > data/static-nodes.json
-                    # # cat build/static-nodes.json
-                    # kubectl create configmap static-nodes-config --from-file=data/static-nodes.json -n {{ .Release.Namespace }} --dry-run=client -o yaml | kubectl apply -f -
 
                     # Check if newStaticNode already exists in existingStaticNodes
                     if ! echo "$existingStaticNodes" | jq 'contains(["'"$newStaticNode"'"])' | grep -q true; then
                         existingStaticNodes=$(jq ". + [\"$newStaticNode\"]" <<< "$existingStaticNodes")
                         echo "$existingStaticNodes" > ./static-nodes.json
-                        kubectl create configmap static-nodes-config --from-file=./static-nodes.json -n {{ .Release.Namespace }} --dry-run=client -o yaml | kubectl apply -f -
+                        kubectl create configmap static-nodes-config --from-file=./static-nodes.json -n {{ .Release.Namespace }} --dry-run=client -o yaml | kubectl replace -f -
                     fi
-                    ####################################################################################################
 
                     echo "SN-2"
                     cat ./static-nodes.json
-                    echo "FINISH #######################################"
+                    echo "# FINISH CM-IF #"
                 else
                     echo "ConfigMap $configmap_name does not exist in namespace {{ .Release.Namespace }}. Creating one."
                     
@@ -193,8 +211,9 @@ spec:
                     echo "]" >> "./static-nodes.json"
                     
                     kubectl create configmap static-nodes-config --from-file=./static-nodes.json -n {{ .Release.Namespace }}
+                    echo "# FINISH CM-ELSE #"
                 fi
-
+                
                 echo "# COMPLETED PRE-HOOK #"
       volumes:
         - name: scripts-volume
diff --git a/platforms/quorum/charts/gen/templates/job.yaml b/platforms/quorum/charts/gen/templates/job.yaml
--- a/platforms/quorum/charts/gen/templates/job.yaml
+++ b/platforms/quorum/charts/gen/templates/job.yaml
@@ -1,32 +1,3 @@
-# apiVersion: v1
-# kind: Namespace
-# metadata:
-#   name: gen
-
-# kubectl create ns genesis
-# kubectl delete ns genesis
----
-# ---
-# apiVersion: v1
-# kind: Pod
-# metadata:
-#   name: quorum-genesis-pod
-#   namespace: genesis
-# spec:
-#   containers:
-#   - name: quorum-genesis-con
-#     image: ghcr.io/hyperledger/bevel-k8s-hooks:qgt-0.2.12
-#     command: ["tail", "-f", "/dev/null"]
-#     ports:
-#     - containerPort: 80
-#   # restartPolicy: Always
-
-# apiVersion: v1
-# kind: Pod
-# metadata:
-#   name: first
-#   namespace: genesis
-
 ---
 apiVersion: batch/v1
 kind: Job
@@ -58,8 +29,8 @@ spec:
       serviceAccountName: {{ .Values.global.serviceAccountName }}
       restartPolicy: OnFailure
       containers:
-        - name:  generate-genesis # first-con
-          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}" # consensys/quorum-k8s-hooks:qgt-0.2.12
+        - name:  generate-genesis
+          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
           securityContext:
             runAsUser: 0
           imagePullPolicy: {{ .Values.image.pullPolicy }}
@@ -90,95 +61,122 @@ spec:
                 . /scripts/bevel-vault.sh
                 # echo "Generate customize token."
                 vaultBevelFunc "init"
-                
-                # Function to push data to vault
+
                 safeWriteSecret() {
-                  local dir="$1"
+                  local key="$1"
                   local fpath="$2"
-                  local deployment="vault" # vault | local
-                  
-                  # Check if all required files exist
-                  local required_files=("accountAddress" "accountKeystore" "accountPassword" "accountPrivateKey" "address" "nodekey" "nodekey.pub")
-                  for file in "${required_files[@]}"; do
-                    if [ ! -f "${dir}/${file}" ]; then
-                      echo "Error: File '${file}' not found in '${dir}'" >&2
-                      return 1
-                    fi
-                  done
-                  
-                  # Read data from files
-                  local node_address=$(cat "${dir}/address")
-                  local node_key=$(cat "${dir}/nodekey")
-                  local node_key_pub=$(cat "${dir}/nodekey.pub")
-                  local account_private_key=$(cat "${dir}/accountPrivateKey")
-                  local account_password=$(cat "${dir}/accountPassword")
-                  local account_keystore_base64=$(cat "${dir}/accountKeystore" | base64 -w 0)
-                  local account_address=$(cat "${dir}/accountAddress")
-                  
-                  # Construct JSON payload
-                  echo "
-                    {
-                      \"data\":
-                        {
-                          \"nodeAddress\": \"${node_address}\",
-                          \"nodeKey\": \"${node_key}\",
-                          \"nodeKeyPub\": \"${node_key_pub}\",
-                          \"accountPrivateKey\": \"${account_private_key}\",
-                          \"accountPassword\": \"${account_password}\",
-                          \"accountKeystore_base64\": \"${account_keystore_base64}\",
-                          \"accountAddress\": \"${account_address}\"
-                        }
-                    }" > nodePayload.json
+                
+                  vaultBevelFunc "readJson" "${VAULT_SECRET_ENGINE}/${VAULT_SECRET_PREFIX}/${key}"
+                  if [ "$SECRETS_AVAILABLE" == "yes" ]
+                    then
+                      echo "Present in the vault"
+                      
+                      local accountAddress=$(echo ${VAULT_SECRET} | jq -r '.["accountAddress"]')
+                      local accountKeystore=$(echo ${VAULT_SECRET} | jq -r '.["accountKeystore_base64"]' | base64 -d)
+                      local accountPassword=$(echo ${VAULT_SECRET} | jq -r '.["accountPassword"]')
+                      local accountPrivateKey=$(echo ${VAULT_SECRET} | jq -r '.["accountPrivateKey"]')
+                      local address=$(echo ${VAULT_SECRET} | jq -r '.["nodeAddress"]')
+                      local nodeKey=$(echo ${VAULT_SECRET} | jq -r '.["nodeKey"]')
+                      local nodekey_pub=$(echo ${VAULT_SECRET} | jq -r '.["nodeKeyPub"]')
+
+                      if ! kubectl get secret goquorum-node-validator-${i}-keys --namespace {{ .Release.Namespace }} &> /dev/null; then                      
+                        kubectl create secret generic goquorum-node-validator-${i}-keys --namespace {{ .Release.Namespace }} \
+                        --from-literal=accountAddress=${accountAddress} \
+                        --from-literal=accountKeystore=${accountKeystore} \
+                        --from-literal=accountPassword=${accountPassword} \
+                        --from-literal=accountPrivateKey=${accountPrivateKey} \
+                        --from-literal=address=${address} \
+                        --from-literal=nodekey=${nodeKey} \
+                        --from-literal=nodekey.pub=${nodekey_pub}
+                      fi
+                  else
+                    echo "Absent in the vault"
+                    # Check if all required files exist
+                    local required_files=("accountAddress" "accountKeystore" "accountPassword" "accountPrivateKey" "address" "nodekey" "nodekey.pub")
+                    for file in "${required_files[@]}"; do
+                      if [ ! -f "${fpath}/${file}" ]; then
+                        echo "Error: File '${file}' not found in '${fpath}'" >&2
+                        return 1
+                      fi
+                    done
                     
-                  # Push data to vault
-                  vaultBevelFunc 'write' "${VAULT_SECRET_ENGINE}/${VAULT_SECRET_PREFIX}/${fpath}" 'nodePayload.json'
-                }
-                  
-                safeWriteGenesis() {
-                  local dir="$1"
-                  local fpath="$2"
-                  local deployment="vault"
-                  
-                  local required_files=("genesis.json" "static-nodes.json")
-                  for file in "${required_files[@]}"; do
-                    if [ ! -f "${dir}/${file}" ]; then
-                      echo "Error: File '${file}' not found in '${dir}'" >&2
-                      return 1
-                    fi
-                  done
-                  
-                  # Read data from files
-                  local genesis_base64=$(cat "${dir}/genesis.json" | base64 -w 0)
-                  
-                  # Construct JSON payload
-                  echo "
-                    {
-                      \"data\":
+                    # Read data from files
+                    local node_address=$(cat "${fpath}/address")
+                    local node_key=$(cat "${fpath}/nodekey")
+                    local node_key_pub=$(cat "${fpath}/nodekey.pub")
+                    local account_private_key=$(cat "${fpath}/accountPrivateKey")
+                    local account_password=$(cat "${fpath}/accountPassword")
+                    local account_keystore_base64=$(cat "${fpath}/accountKeystore" | base64 -w 0)
+                    local account_address=$(cat "${fpath}/accountAddress")
+                    
+                    # Construct JSON payload
+                    echo "
                       {
-                        \"genesis_base64\": \"${genesis_base64}\"
-                      }
-                    }" > genesisPayload.json
+                        \"data\":
+                          {
+                            \"nodeAddress\": \"${node_address}\",
+                            \"nodeKey\": \"${node_key}\",
+                            \"nodeKeyPub\": \"${node_key_pub}\",
+                            \"accountPrivateKey\": \"${account_private_key}\",
+                            \"accountPassword\": \"${account_password}\",
+                            \"accountKeystore_base64\": \"${account_keystore_base64}\",
+                            \"accountAddress\": \"${account_address}\"
+                          }
+                      }" > nodePayload.json
+                      
+                    # Push data to vault
+                    vaultBevelFunc 'write' "${VAULT_SECRET_ENGINE}/${VAULT_SECRET_PREFIX}/${key}" 'nodePayload.json'
+                  fi
+                }
+                safeWriteGenesis() {
+                  local key="$1" # quorum-genesis # quorum-node-validator-${i}-keys
+                  local fpath="$2" # $FOLDER_PATH/goQuorum # ${current_validator_dir}
+                  
+                  vaultBevelFunc "readJson" "${VAULT_SECRET_ENGINE}/${VAULT_SECRET_PREFIX}/${key}"
+                  if [ "$SECRETS_AVAILABLE" == "yes" ]
+                  then
+                    # local genesis=$(echo ${VAULT_SECRET} | jq -r '.["genesis_base64"]' | base64 -d)
+                    echo "HERE : ${genesis}"                    
+                    echo ${VAULT_SECRET} | jq -r '.["genesis_base64"]' | base64 -d > ./genesis.json
+                    if ! kubectl get configmap "genesis-config" -n {{ .Release.Namespace }} &> /dev/null; then
+                      kubectl create configmap "quorum-genesis" --from-file=./genesis.json -n {{ .Release.Namespace }}
+                    fi
+                  else
+                    local required_files=("genesis.json" "static-nodes.json")
+                    for file in "${required_files[@]}"; do
+                      if [ ! -f "${fpath}/${file}" ]; then
+                        echo "Error: File '${file}' not found in '${fpath}'" >&2
+                        return 1
+                      fi
+                    done
                     
-                  # Push data to vault
-                  vaultBevelFunc 'write' "${VAULT_SECRET_ENGINE}/${VAULT_SECRET_PREFIX}/${fpath}" 'genesisPayload.json'
+                    # Read data from files
+                    local genesis_base64=$(cat "${fpath}/genesis.json" | base64 -w 0)
+                    
+                    # Construct JSON payload
+                    echo "
+                      {
+                        \"data\":
+                        {
+                          \"genesis_base64\": \"${genesis_base64}\"
+                        }
+                      }" > genesisPayload.json
+                      
+                    # Push data to vault
+                    vaultBevelFunc 'write' "${VAULT_SECRET_ENGINE}/${VAULT_SECRET_PREFIX}/${key}" 'genesisPayload.json'
+                  fi
+                }
+              else
+                safeWriteSecret() {
+                  # Placeholder:
+                  # - Implement code to fetch the keys if using any cloud-native service or platform different from HashiCorp to store the keys
+                  # - After fetching the keys, create Kubernetes secrets from them
+                  # - For guidance, refer to the code written for HashiCorp Vault for the same purpose
+                  return 0
                 }
               fi
 
               # # Run the command and capture the output
-              # FOLDER_PATH=$(quorum-genesis-tool \
-              #   --consensus ibft \
-              #   --chainID 1337 \
-              #   --blockperiod 5 \
-              #   --requestTimeout 10 \
-              #   --epochLength 30000 \
-              #   --difficulty 1 \
-              #   --gasLimit '0xFFFFFF' \
-              #   --coinbase '0x0000000000000000000000000000000000000000' \
-              #   --validators 5 \
-              #   --members 0 \
-              #   --bootnodes 0 \
-              #   --outputPath 'artifacts')
-              # Run the command and capture the output
               FOLDER_PATH=$(quorum-genesis-tool --consensus {{ .Values.rawGenesisConfig.genesis.config.algorithm.consensus }} \
                 {{ if .Values.rawGenesisConfig.blockchain.nodes.generate }} --validators {{ .Values.rawGenesisConfig.blockchain.nodes.count }} {{ else }} --validators 0 {{ end }} \
                 --members 0 --bootnodes 0 --chainID {{ .Values.rawGenesisConfig.genesis.config.chainId }} --blockperiod {{ .Values.rawGenesisConfig.genesis.config.algorithm.blockperiodseconds }} \
@@ -187,48 +185,51 @@ spec:
                 --gasLimit {{ .Values.rawGenesisConfig.genesis.gasLimit }} --coinbase {{ .Values.rawGenesisConfig.genesis.coinbase }} \
                 {{ if .Values.rawGenesisConfig.blockchain.accountPassword }} --accountPassword {{ .Values.rawGenesisConfig.blockchain.accountPassword }} {{ end }} \
                 --quickstartDevAccounts {{ .Values.rawGenesisConfig.genesis.includeQuickStartAccounts }} \
-                --outputPath 'artifacts')
+                --outputPath /generated-config | tail -1 | sed -e "s/^Artifacts in folder: //")
 
-              # Extract the directory path from the output
-              directory=$(echo "$FOLDER_PATH" | grep -o 'artifacts/.*')
-              # Print the directory path
-              echo "Directory path: $directory" # NR
-              mv $directory/* artifacts
+              if ! kubectl get configmap "genesis-config" -n {{ .Release.Namespace }} &> /dev/null; then
+                kubectl create configmap "genesis-config" --namespace {{ .Release.Namespace }} --from-file="$FOLDER_PATH/goQuorum/genesis.json"
+              fi
 
               # Count the number of validators based on their directories
-              validator_count=$(ls -d ./artifacts/validator* | wc -l)
+              validator_count=$(ls -d $FOLDER_PATH/validator* | wc -l)
               echo "validator_count: $validator_count"
 
               # Iterate through the validators using a for loop
               for ((i = 0; i < validator_count; i++)); do
                 # Access the current validator directory using its index
-                current_validator_dir="./artifacts/validator${i}"
+                current_validator_dir="$FOLDER_PATH/validator${i}"
 
-                kubectl create secret generic goquorum-node-validator-${i}-keys --namespace {{ .Release.Namespace }} \
-                  --from-literal=accountAddress=$(cat "${current_validator_dir}/accountAddress") \
-                  --from-literal=accountKeystore=$(cat "${current_validator_dir}/accountKeystore") \
-                  --from-literal=accountPassword=$(cat "${current_validator_dir}/accountPassword") \
-                  --from-literal=accountPrivateKey=$(cat "${current_validator_dir}/accountPrivateKey") \
-                  --from-literal=address=$(cat "${current_validator_dir}/address") \
-                  --from-literal=nodekey=$(cat "${current_validator_dir}/nodekey") \
-                  --from-literal=nodekey.pub=$(cat "${current_validator_dir}/nodekey.pub")
+{{- if and (ne .Values.global.cluster.provider "minikube") (.Values.global.cluster.cloudNativeServices) }}
+                safeWriteSecret besu-node-validator-${i}-nodekey ${current_validator_dir}/nodekey
+                safeWriteSecret besu-node-validator-${i}-nodekeypub ${current_validator_dir}/nodekey.pub 
+                safeWriteSecret besu-node-validator-${i}-enode ${current_validator_dir}/nodekey.pub 
+                safeWriteSecret besu-node-validator-${i}-address ${current_validator_dir}/address
+                kubectl create configmap --namespace {{ .Release.Namespace }} "besu-node-validator-${i}-address" --from-file=address=${current_validator_dir}/address
 
-                # if [ "$VAULT_TYPE" == "hashicorp" ]; then
-                #   # Push data to vault
-                #   safeWriteSecret "${current_validator_dir}" "quorum-node-validator-${i}-keys"
-                # fi
-                safeWriteSecret "${current_validator_dir}" "quorum-node-validator-${i}-keys"
+                safeWriteSecret besu-node-validator-${i}-accountPrivateKey ${current_validator_dir}/accountPrivateKey
+                safeWriteSecret besu-node-validator-${i}-accountPassword ${current_validator_dir}/accountPassword
+                safeWriteSecret besu-node-validator-${i}-accountKeystore ${current_validator_dir}/accountKeystore 
+                safeWriteSecret besu-node-validator-${i}-accountAddress ${current_validator_dir}/accountAddress 
+{{- else }}
+                safeWriteSecret "quorum-node-validator-${i}-keys" "${current_validator_dir}"
+                safeWriteGenesis "quorum-genesis" "$FOLDER_PATH/goQuorum"
+{{- end }}
+
+                if ! kubectl get secret goquorum-node-validator-${i}-keys -n {{ .Release.Namespace }} &> /dev/null; then
+                  echo "Creating directly"
+                  kubectl create secret generic goquorum-node-validator-${i}-keys --namespace {{ .Release.Namespace }} \
+                    --from-literal=accountAddress=$(cat "${current_validator_dir}/accountAddress") \
+                    --from-literal=accountKeystore=$(cat "${current_validator_dir}/accountKeystore") \
+                    --from-literal=accountPassword=$(cat "${current_validator_dir}/accountPassword") \
+                    --from-literal=accountPrivateKey=$(cat "${current_validator_dir}/accountPrivateKey") \
+                    --from-literal=address=$(cat "${current_validator_dir}/address") \
+                    --from-literal=nodekey=$(cat "${current_validator_dir}/nodekey") \
+                    --from-literal=nodekey.pub=$(cat "${current_validator_dir}/nodekey.pub")
+                fi
               done
 
-              kubectl create configmap genesis-config --namespace {{ .Release.Namespace }} --from-file="./artifacts/goQuorum/genesis.json"
-              # if [ "$VAULT_TYPE" == "hashicorp" ]; then
-              #   safeWriteGenesis "./artifacts/goQuorum" "quorum-genesis"
-              # fi
-              safeWriteGenesis "./artifacts/goQuorum" "quorum-genesis"
-
-              echo "# DONE #"
-
-              # tail -f /dev/null
+              echo "# Completed #"
       volumes:
         - name: scripts-volume
           configMap:
