a1

diff --git a/platforms/substrate/charts/substrate-genesis/templates/genesis.yaml b/platforms/substrate/charts/substrate-genesis/templates/genesis.yaml
--- a/platforms/substrate/charts/substrate-genesis/templates/genesis.yaml
+++ b/platforms/substrate/charts/substrate-genesis/templates/genesis.yaml
@@ -68,7 +68,6 @@ spec:
 
           #!/usr/bin/env bash
 
-          # STEP-1
           echo "Step 1: Check if the node image is available and install necessary packages if needed."
           {{- if ne $.Values.node.image "docker.io/paritytech/substrate-playground-template-node-template" }}
             # Install necessary packages using custom package manager script
@@ -92,14 +91,12 @@ spec:
           mv kubectl /usr/local/bin/
           kubectl version --client
 
-          # STEP-2
           echo "Step 2: Execute the provided command to generate the genesis block."
           mkdir certcheck
           command={{ $.Values.node.command }}
           echo "Generate genesis"
           GENESIS=$($command build-spec --disable-default-bootnode --chain local)
 
-          # STEP-3
           echo "Step 3: Edit genesis configuration."
           # Set values
           GENESIS=$(echo $GENESIS | jq '.name |= {{ .Values.chain | quote }}')
@@ -114,7 +111,6 @@ spec:
             GENESIS=$(echo $GENESIS | jq '.genesis.runtime.membership.members |= []')
           {{- end }}
 
-          # STEP-4
           echo "Step 4: Generate sudo key with Sr25519 scheme and add sudo account key and balance into genesis."
           # Generate sudo key with Sr25519 scheme        
           $command key generate --scheme Sr25519 --output-type json >> certcheck/sudoKeygenOutput.json
@@ -124,63 +120,94 @@ spec:
           GENESIS=$(echo $GENESIS | jq --arg sudo $SUDO_ADDR --arg balance 1152921504606846976 '.genesis.runtime.balances.balances += [[$sudo, ($balance | tonumber)]]')
           GENESIS=$(echo $GENESIS | jq --arg sudo $SUDO_ADDR '.genesis.runtime.sudo.key |= $sudo')
 
-          # STEP-5
           echo "Step 5: Insert AURA & GRANDPA keys into genesis for validators."
           echo "Inserting keys into genesis for validators"
-          for ((i=1; i<= {{ $.Values.node.validatorCount }}; i++)); do
+          for ((i=1; i<= {{ $.Values.node.validator.count }}; i++)); do
             secret_data=$(kubectl get secret "substrate-node-validator-${i}-keys" --namespace {{ .Release.Namespace }} -o json | jq -r '.data["substrate-node-keys"]' | base64 -d)
             
             # Check if secret_data is empty or not
-              if [ -n "$secret_data" ]; then
-                  echo "Parse aura_addr from decoded JSON"
-                  # Extract aura_addr and grandpa_addr
-                  aura_addr=$(echo "$secret_data" | jq -r '.data.aura_addr')
-                  grandpa_addr=$(echo "$secret_data" | jq -r '.data.grandpa_addr')
-                  
-                  # Check if extraction successful
-                  if [ -n "$aura_addr" ] && [ -n "$grandpa_addr" ]; then
-                      # Insert aura_addr keys into GENESIS JSON
-                      GENESIS=$(echo "$GENESIS" | jq --arg aura "$aura_addr" '.genesis.runtime.aura.authorities += [$aura]')
-                      GENESIS=$(echo "$GENESIS" | jq --arg grandpa "$grandpa_addr" '.genesis.runtime.grandpa.authorities += [[$grandpa, 1]]')
-                  else
-                      echo "Error: Unable to retrieve aura_addr or grandpa_addr key"
-                  fi
+            if [ -n "$secret_data" ]; then
+              # Extract aura_addr and grandpa_addr
+              aura_addr=$(echo "$secret_data" | jq -r '.data.aura_addr')
+              grandpa_addr=$(echo "$secret_data" | jq -r '.data.grandpa_addr')
+              
+              # Check if extraction successful
+              if [ -n "$aura_addr" ] && [ -n "$grandpa_addr" ]; then
+                # Insert aura_addr keys into GENESIS JSON
+                GENESIS=$(echo "$GENESIS" | jq --arg aura "$aura_addr" '.genesis.runtime.aura.authorities += [$aura]')
+                GENESIS=$(echo "$GENESIS" | jq --arg grandpa "$grandpa_addr" '.genesis.runtime.grandpa.authorities += [[$grandpa, 1]]')
               else
-                  echo "Error: Unable to retrieve data."
+                echo "Error: Unable to retrieve aura_addr or grandpa_addr key"
               fi
+            else
+              echo "Error: Unable to retrieve data."
+            fi
           done
 
-          # STEP-6
+          # Initialize an array to store each nodes' Kubernetes secret name
+          secret_names=$(kubectl get secret -n {{ .Release.Namespace }} | grep substrate-node | awk '{print $1}')
+          declare -a nodes
+          while IFS= read -r line; do
+            nodes+=("$line")
+          done <<< "$secret_names"
+
           echo "Step 6: Adding member accounts and their balances to genesis."
-          {{- range $idx, $member := .Values.node.members }}
-            this_account_addr=$(kubectl get secret "substrate-node-{{ $member.name }}-keys" --namespace {{ $.Release.Namespace }} -o json | jq -r '.data["substrate-node-keys"]' | base64 -d | jq -r '.data.account_addr')
+          for ((i=1; i<= {{ $.Values.node.member.count }}; i++)); do
+            account_addr=$(kubectl get secret "substrate-node-member-$i-keys" --namespace {{ .Release.Namespace }} -o json | jq -r '.data["substrate-node-keys"]' | base64 -d | jq -r '.data.account_addr')
             # Add account address and balance into genesis block
-            GENESIS=$(echo "$GENESIS" | jq --arg account_id "${this_account_addr}" --arg balance {{ $member.balance }} '.genesis.runtime.balances.balances += [[$account_id, ($balance | tonumber)]]')
-            GENESIS=$(echo "$GENESIS" | jq --arg account_id "${this_account_addr}" '.genesis.runtime.membership.members += [$account_id]')
+            GENESIS=$(echo "$GENESIS" | jq --arg account_id "$account_addr" --arg balance {{ $.Values.node.member.balance }} '.genesis.runtime.balances.balances += [[$account_id, ($balance | tonumber)]]')
+            GENESIS=$(echo "$GENESIS" | jq --arg account_id "$account_addr" '.genesis.runtime.membership.members += [$account_id]')
             
             # Loop through each node to add authorization for the current member
-            {{- range $member.nodes }}
-              this_node={{ . }}
+            for node in "${nodes[@]}"; do
               # Retrieve node ID for the current node
-              this_node_id=$(kubectl get secret "substrate-node-${this_node}-keys" --namespace {{ $.Release.Namespace }} -o json | jq -r '.data["substrate-node-keys"]' | base64 -d | jq -r '.data.node_id')
+              node_id=$(kubectl get secret "$node" --namespace {{ .Release.Namespace }} -o json | jq -r '.data["substrate-node-keys"]' | base64 -d | jq -r '.data.node_id')
               
               # Convert node ID to base58 format
-              this_node_base58=$(echo -n "${this_node_id}" | base58 -d | xxd -p | tr -d '[:space:]' | tr '[:lower:]' '[:upper:]')
+              base58=$(echo -n "$node_id" | base58 -d | xxd -p | tr -d '[:space:]' | tr '[:lower:]' '[:upper:]')
               
               # Split the base58 string into an array of bytes
-              arr_this_node_id=($(echo ${this_node_base58} | fold -w2))
+              arr_node_id=($(echo $base58 | fold -w2))
               
               # Add authorization for the current member to the node
-              GENESIS=$(echo $GENESIS | jq --arg owner "${this_account_addr}" '.genesis.runtime.nodeAuthorization.nodes += [[[], $owner]]')
-              for byte in "${arr_this_node_id[@]}"
+              GENESIS=$(echo $GENESIS | jq --arg owner "$account_addr" '.genesis.runtime.nodeAuthorization.nodes += [[[], $owner]]')
+              for byte in "${arr_node_id[@]}"
               do
                 # Add each byte of the node ID to the authorization
                 GENESIS=$(echo $GENESIS | jq --arg byte $(echo "obase=10; ibase=16; $byte" | bc) '.genesis.runtime.nodeAuthorization.nodes[-1][0] += [($byte | tonumber)]')
               done
-            {{- end }}          
-          {{- end }}
+            done
+          done
           
-          # STEP-7
+          # echo "Step 6: Adding member accounts and their balances to genesis."
+          # {{- range $idx, $member := .Values.node.members }}
+          #   this_account_addr=$(kubectl get secret "substrate-node-{{ $member.name }}-keys" --namespace {{ $.Release.Namespace }} -o json | jq -r '.data["substrate-node-keys"]' | base64 -d | jq -r '.data.account_addr')
+          #   # Add account address and balance into genesis block
+          #   GENESIS=$(echo "$GENESIS" | jq --arg account_id "${this_account_addr}" --arg balance {{ $member.balance }} '.genesis.runtime.balances.balances += [[$account_id, ($balance | tonumber)]]')
+          #   GENESIS=$(echo "$GENESIS" | jq --arg account_id "${this_account_addr}" '.genesis.runtime.membership.members += [$account_id]')
+            
+          #   # Loop through each node to add authorization for the current member
+          #   {{- range $member.nodes }}
+          #     this_node={{ . }}
+          #     # Retrieve node ID for the current node
+          #     this_node_id=$(kubectl get secret "substrate-node-${this_node}-keys" --namespace {{ $.Release.Namespace }} -o json | jq -r '.data["substrate-node-keys"]' | base64 -d | jq -r '.data.node_id')
+              
+          #     # Convert node ID to base58 format
+          #     this_node_base58=$(echo -n "${this_node_id}" | base58 -d | xxd -p | tr -d '[:space:]' | tr '[:lower:]' '[:upper:]')
+              
+          #     # Split the base58 string into an array of bytes
+          #     arr_this_node_id=($(echo ${this_node_base58} | fold -w2))
+              
+          #     # Add authorization for the current member to the node
+          #     GENESIS=$(echo $GENESIS | jq --arg owner "${this_account_addr}" '.genesis.runtime.nodeAuthorization.nodes += [[[], $owner]]')
+          #     for byte in "${arr_this_node_id[@]}"
+          #     do
+          #       # Add each byte of the node ID to the authorization
+          #       GENESIS=$(echo $GENESIS | jq --arg byte $(echo "obase=10; ibase=16; $byte" | bc) '.genesis.runtime.nodeAuthorization.nodes[-1][0] += [($byte | tonumber)]')
+          #     done
+          #   {{- end }}          
+          # {{- end }}
+          
           echo "Step 7: Update the format of the modified genesis JSON and create a config map if it doesn't exist."
           # Write the modified genesis JSON to a file
           echo "$GENESIS" > certcheck/genesis.json
@@ -189,11 +216,15 @@ spec:
           GENESIS=$($command build-spec --disable-default-bootnode --raw --chain certcheck/genesis.json)
           echo "$GENESIS" > certcheck/genesis_raw.json
           # Encode the raw genesis JSON to base64
-          cat certcheck/genesis_raw.json | base64 -w0 > certcheck/genesis_base64
+          # cat certcheck/genesis_raw.json | base64 -w0 > certcheck/genesis_base64 # No need to encode it if you wanna store genesis as a K8s secret
+
           # Create the config map "substrate-genesis" using the base64 encoded genesis JSON and sudoKeygenOutput.json if it doesn't exist
-          if ! kubectl get configmap "substrate-genesis" --namespace {{ .Release.Namespace }} &> /dev/null; then
-            kubectl create configmap "substrate-genesis" --namespace {{ .Release.Namespace }} --from-file=genesis="${MOUNT_PATH}/genesis_base64" --from-file=sudoKeygenOutput="${MOUNT_PATH}/sudoKeygenOutput.json"
+          if ! kubectl get secret "substrate-genesis" --namespace {{ .Release.Namespace }} &> /dev/null; then
+            kubectl create secret generic "substrate-genesis" --namespace {{ .Release.Namespace }} --from-file=genesis="${MOUNT_PATH}/genesis_raw.json" --from-file=sudoKeygenOutput="${MOUNT_PATH}/sudoKeygenOutput.json"
           fi
+          # if ! kubectl get configmap "substrate-genesis" --namespace {{ .Release.Namespace }} &> /dev/null; then
+          #   kubectl create configmap "substrate-genesis" --namespace {{ .Release.Namespace }} --from-file=genesis="${MOUNT_PATH}/genesis_base64" --from-file=sudoKeygenOutput="${MOUNT_PATH}/sudoKeygenOutput.json"
+          # fi
 
           echo "COMPLETED!"
       volumes:
